name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  # PR Validation
  validate-pr:
    name: Validate PR
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
      - run: npm run lint -- --format=github
      - run: npm test -- --coverage --reporters=default --reporters=jest-github-actions
      - run: npm run build
      - run: docker build -t ccep-mach-microservice:pr-validate .

  # Deployment on main branch
  deploy:
    name: Deploy Docker on main
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: validate-pr

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
      - run: npm run lint
      - run: npm test -- --coverage
      - run: npm run build

      # Build Docker image
      - run: docker build -t your-dockerhub-username/ccep-mach-microservice:latest .

      # Login to DockerHub
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push Docker image
      - run: docker push your-dockerhub-username/ccep-mach-microservice:latest

      # Optional: Deploy to Kubernetes
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.30.0

      - name: Configure Kubeconfig
        run: echo "${{ secrets.KUBECONFIG_CONTENT }}" > kubeconfig && export KUBECONFIG=kubeconfig

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/ccep-mach ccep-mach=your-dockerhub-username/ccep-mach-microservice:latest
          kubectl rollout status deployment/ccep-mach
